
name: PR Test

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World!"

    - name: Run external scropt
      run: bash script.sh
  
